language: rust

rust:
  - "nightly"
#  - "beta"
#  - "stable"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

sudo: false

cache: cargo

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=/usr/lib/ccache:$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin:$PATH

script:
  - rustc --version
  - cargo --version
  - travis-cargo build
  - travis-cargo test
  - travis-cargo --only nightly bench
  - travis-cargo doc

after_success:
  - if [ ${TRAVIS_OS_NAME} != "osx" ]; then travis-cargo --only nightly doc-upload; fi; true
  - if [ ${TRAVIS_OS_NAME} != "osx" ]; then travis-cargo coveralls --no-sudo --verify --exclude-pattern="test/,target/debug/build/"; fi; true

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "U0ng3AXIvyiAUGKa8fHFSw3uyMyOfe1HWgJkL50hdC4bKalVmuJWZlZJInnodnVp6Ce1aBPSuQ1oY5R6wHr+jx0gWIEOopUhRAV4k4DMBYpZVUATbeM3SV4LFWzjf/JoZe25eZbMMaZ/BfWgVUM7g4lht/So6vumZzb17r+PUpB+JnjmwLFGk3k+JiL9TspBNCaeZW+MCPIqF5BXXXnmvclVmQPvtKYI20EGvvg/3755+FnSRlxuvpvEOhzjJmsZZQbWGHdg5g7yoC5T1akLvetMcOdtdLbgL+6pgkJvWxN1l6XIhZPSzWreWlh/6Nglojr1/RNFJE3+2LEXJIUmeAo/h7w7XdNB/fnPXCtF9gHa47DgzK45m6t9rfwyewG1qCV+EGqVIw5I7lfMaQNKOwpFPTd7t7c5MLc2FY7WwSJ+enSa8AznhQhuzx0fAaBuoBT6OMAA/gJwp6F9UKvjtZ8zS6OJOsjBUcv4X+Vjobz6fgeKc9/etnK4ZRdY/SR/Kx64NX6vLj/PzAo4mMZjKhP2gpEp4vDyBQmQNB5y5HA3PSwho8GePZOIsJH7XxOStBNNSyp30hr4Lo8ovWnNow8DopgHDGIMO8X3fBMVxpR4OHxnSlS8r1V2yeCbE329c1/I3qopXIlu/fNxES2/BMEue4XeWtV+DZtqOZXB5Fc="
