[package]
name = "dagon"
version = "0.1.0"
authors = ["André-Patrick Bubel <code@andre-bubel.de>"]

[dependencies]
rand = "*"
nalgebra = "*"
num = "*"
rmp-serialize = "*"
rustc-serialize = "0.3"
acacia = { git = "https://github.com/aepsil0n/acacia" }
